version: '3'
services:
  postgres-db:
    image: postgres:15-alpine
    ports:
      - "6543:5432"
    volumes:
      - postgres-db:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: admin
      POSTGRES_PASSWORD: admin
      POSTGRES_DB: blog
    restart: unless-stopped

  pgadmin:
    container_name: pgAdmin
    image: dpage/pgadmin4
    depends_on:
      - postgres-db
    ports:
      - "5555:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.ru
      PGADMIN_DEFAULT_PASSWORD: admin
    restart: unless-stopped

  mongodb:
    image: mongo:5.0
    ports:
      - 27017:27017
    volumes:
      - ~/apps/mongo:/data/db
    environment:
      - MONGO_INITDB_ROOT_USERNAME=admin
      - MONGO_INITDB_ROOT_PASSWORD=admin

volumes:
  postgres-db:
    driver: local